### ISSUE TITLE
Attempting to mine via rpc crashes the wallet

### ISSUE THREAD

**Issue by ghost** [gamecashproject/gcash#2]
I was attempting to mine via rpc using cpuminer-opt I created a batch file to launch the wallet with the necessary commands including server rpcuser rpcpassword and rpcallowip all with correct variables. After pointing cpuminer-opt to the rpcserver on port 58854 using a batch file with variables that match the ones set in the batch file I used to launch the wallet. after launching the wallet then cpuminer-opt via its batch file the wallet crashes and I get this error on cpuminer-opt "HTTP request failed: Recv failure: Connection was reset" I attempted using getblocktemplate longpoll and getwork but all 3 failed.

**Comment by gamecashproject** [comment]
Use "pooler-cpuminer-2.5.0" or "cpuminer multi-rel1.0.9" for CPU mining, or cgminer 3.7.2 forg GPU mining

**Comment by ghost** [comment]
Confirmed that the issue was with cpuminer-opt.
